### ISSUE TITLE
Installation Issue with tensorflow-gpu

### ISSUE THREAD

**Issue by buttercutter** [epignatelli/jaxboard#2]
Could you please update the pypi package because https://pypi.org/project/tensorflow-gpu/ is no longer maintained and had been replaced with `tensorflow` instead ?

```
 ~  pip install jaxboard                                                             
Defaulting to user installation because normal site-packages is not writeable
Collecting jaxboard
  Using cached jaxboard-0.0.1.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/lib/python3.10/site-packages (from jaxboard) (1.24.1)
Requirement already satisfied: matplotlib in /usr/lib/python3.10/site-packages (from jaxboard) (3.6.2)
Requirement already satisfied: tensorboard in /usr/lib/python3.10/site-packages (from jaxboard) (2.11.0)
Requirement already satisfied: tensorflow>=1.15.0 in /usr/lib/python3.10/site-packages (from jaxboard) (2.11.0)
Collecting tensorflow-gpu>=1.15.0
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/usr/lib/python3.10/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wxd30vdd/tensorflow-gpu_7b274b6a44bf4cca85d4ea3315a1dc2f/setup.py", line 40, in <module>
          setuptools.setup()
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 78, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 874, in parse_config_files
          self._finalize_requires()
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 581, in _finalize_requires
          self._move_install_requirements_markers()
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 621, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3095, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
 !  ~                                                                      
 !  ~  pip install tensorflow-gpu                                          
Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow-gpu
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/usr/lib/python3.10/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2lhycgry/tensorflow-gpu_d19ec0dfc9f14a06817474054f06f692/setup.py", line 40, in <module>
          setuptools.setup()
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 78, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 874, in parse_config_files
          self._finalize_requires()
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 581, in _finalize_requires
          self._move_install_requirements_markers()
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 621, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3095, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
 !  ~                                                                      
```

**Comment by epignatelli** [comment]
Hey! In am really not maintaining this packages as tensorboard is really hard to work with.
I'll actually archive this repo.

I can see you are using a cached version if `tensorflow-gpu`:
`Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)`

Have you tried ignoring the cache?
`pip install git+https://github.com/epignatelli/jaxboard --no-cache-dir`?

**Comment by buttercutter** [comment]
@epignatelli 

```
moe@t1v-n-ff0a25ed-w-0:~$ pip3 install git+https://github.com/epignatelli/jaxboard --no-cache-dir
Collecting git+https://github.com/epignatelli/jaxboard
  Cloning https://github.com/epignatelli/jaxboard to /tmp/pip-req-build-udtan63o
  Running command git clone -q https://github.com/epignatelli/jaxboard /tmp/pip-req-build-udtan63o
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (1.23.5)
Requirement already satisfied: matplotlib in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (3.6.2)
Requirement already satisfied: tensorboard in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: tensorflow>=1.15.0 in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (2.11.0)
Collecting tensorflow-gpu>=1.15.0
  Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (1.0.6)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (23.0)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (9.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib->jaxboard==0.0.1) (2.4.6)
Requirement already satisfied: python-dateutil>=2.7 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (2.8.2)
Requirement already satisfied: absl-py>=0.4 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (1.3.0)
Requirement already satisfied: grpcio>=1.24.3 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (1.51.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (2.16.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (3.4.1)
Requirement already satisfied: protobuf<4,>=3.9.2 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (3.19.6)
Requirement already satisfied: requests<3,>=2.21.0 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (2.28.2)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard->jaxboard==0.0.1) (62.3.2)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (2.2.2)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard->jaxboard==0.0.1) (0.34.2)
Requirement already satisfied: astunparse>=1.6.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (23.1.21)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (3.8.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: libclang>=13.0.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (15.0.6.1)
Requirement already satisfied: opt-einsum>=2.3.2 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (3.3.0)
Requirement already satisfied: six>=1.12.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (1.16.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (2.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (4.4.0)
Requirement already satisfied: wrapt>=1.11.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1; platform_machine != "arm64" or platform_system != "Darwin" in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (0.30.0)
Requirement already satisfied: python_version>"3.7" in ./.local/lib/python3.8/site-packages (from tensorflow-gpu>=1.15.0->jaxboard==0.0.1) (0.0.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (5.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (0.2.1)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in ./.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->jaxboard==0.0.1) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4; python_version < "3.10" in ./.local/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard->jaxboard==0.0.1) (6.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (2019.11.28)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./.local/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard->jaxboard==0.0.1) (2.1.1)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (0.4.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->jaxboard==0.0.1) (3.1.0)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.8/site-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard->jaxboard==0.0.1) (3.11.0)
Building wheels for collected packages: jaxboard, tensorflow-gpu
  Building wheel for jaxboard (setup.py) ... done
  Created wheel for jaxboard: filename=jaxboard-0.0.1-py3-none-any.whl size=6805 sha256=aab9c25f0c3501bcfbf13f8b2f0cd705e0624e7fd06c3515fc8363b907ef66a7
  Stored in directory: /tmp/pip-ephem-wheel-cache-3fnn9ckv/wheels/e8/0a/3a/253c8b19eb46238f40eb983aae5d508d98ae7472971a47a41f
  Building wheel for tensorflow-gpu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ga_f3nrx
       cwd: /tmp/pip-install-bdbdhbu6/tensorflow-gpu/
  Complete output (17 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py", line 37, in <module>
      raise Exception(TF_REMOVAL_WARNING)
  Exception:
  
  =========================================================
  The "tensorflow-gpu" package has been removed!
  
  Please install "tensorflow" instead.
  
  Other than the name, the two packages have been identical
  since TensorFlow 2.1, or roughly since Sep 2019. For more
  information, see: pypi.org/project/tensorflow-gpu
  =========================================================
  
  
  ----------------------------------------
  ERROR: Failed building wheel for tensorflow-gpu
  Running setup.py clean for tensorflow-gpu
Successfully built jaxboard
Failed to build tensorflow-gpu
Installing collected packages: tensorflow-gpu, jaxboard
    Running setup.py install for tensorflow-gpu ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xobv1v3e/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/moe/.local/include/python3.8/tensorflow-gpu
         cwd: /tmp/pip-install-bdbdhbu6/tensorflow-gpu/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py", line 37, in <module>
        raise Exception(TF_REMOVAL_WARNING)
    Exception:
    
    =========================================================
    The "tensorflow-gpu" package has been removed!
    
    Please install "tensorflow" instead.
    
    Other than the name, the two packages have been identical
    since TensorFlow 2.1, or roughly since Sep 2019. For more
    information, see: pypi.org/project/tensorflow-gpu
    =========================================================
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bdbdhbu6/tensorflow-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xobv1v3e/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/moe/.local/include/python3.8/tensorflow-gpu Check the logs for full command output.
moe@t1v-n-ff0a25ed-w-0:~$ 
```

**Comment by epignatelli** [comment]
I just pushed a new branch without the requirement.
You can find it here: https://github.com/epignatelli/jaxboard/tree/dev/tensorflow-gpu.

`pip install git+https://github.com/epignatelli/jaxboard@dev/tensorflow-gpu`

**Comment by buttercutter** [comment]
Thanks, it works !!

```
moe@t1v-n-ff0a25ed-w-0:~$ pip3 install git+https://github.com/epignatelli/jaxboard@dev/tensorflow-gpu --no-cache-dir
Collecting git+https://github.com/epignatelli/jaxboard@dev/tensorflow-gpu
  Cloning https://github.com/epignatelli/jaxboard (to revision dev/tensorflow-gpu) to /tmp/pip-req-build-_8m92ygy
  Running command git clone -q https://github.com/epignatelli/jaxboard /tmp/pip-req-build-_8m92ygy
  Running command git checkout -b dev/tensorflow-gpu --track origin/dev/tensorflow-gpu
  Switched to a new branch 'dev/tensorflow-gpu'
  Branch 'dev/tensorflow-gpu' set up to track remote branch 'dev/tensorflow-gpu' from 'origin'.
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (1.23.5)
Requirement already satisfied: matplotlib in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (3.6.2)
Requirement already satisfied: tensorboard in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: tensorflow>=1.15.0 in ./.local/lib/python3.8/site-packages (from jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (1.0.6)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (23.0)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (9.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib->jaxboard==0.0.1) (2.4.6)
Requirement already satisfied: python-dateutil>=2.7 in ./.local/lib/python3.8/site-packages (from matplotlib->jaxboard==0.0.1) (2.8.2)
Requirement already satisfied: absl-py>=0.4 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (1.3.0)
Requirement already satisfied: grpcio>=1.24.3 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (1.51.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (2.16.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (3.4.1)
Requirement already satisfied: protobuf<4,>=3.9.2 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (3.19.6)
Requirement already satisfied: requests<3,>=2.21.0 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (2.28.2)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard->jaxboard==0.0.1) (62.3.2)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in ./.local/lib/python3.8/site-packages (from tensorboard->jaxboard==0.0.1) (2.2.2)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard->jaxboard==0.0.1) (0.34.2)
Requirement already satisfied: astunparse>=1.6.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (23.1.21)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (3.8.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: libclang>=13.0.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (15.0.6.1)
Requirement already satisfied: opt-einsum>=2.3.2 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (3.3.0)
Requirement already satisfied: six>=1.12.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (1.16.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (2.11.0)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (2.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (4.4.0)
Requirement already satisfied: wrapt>=1.11.0 in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1; platform_machine != "arm64" or platform_system != "Darwin" in ./.local/lib/python3.8/site-packages (from tensorflow>=1.15.0->jaxboard==0.0.1) (0.30.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (5.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (0.2.1)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in ./.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->jaxboard==0.0.1) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4; python_version < "3.10" in ./.local/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard->jaxboard==0.0.1) (6.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->jaxboard==0.0.1) (2019.11.28)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./.local/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard->jaxboard==0.0.1) (2.1.1)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<3,>=1.6.3->tensorboard->jaxboard==0.0.1) (0.4.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->jaxboard==0.0.1) (3.1.0)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.8/site-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard->jaxboard==0.0.1) (3.11.0)
Building wheels for collected packages: jaxboard
  Building wheel for jaxboard (setup.py) ... done
  Created wheel for jaxboard: filename=jaxboard-0.0.1-py3-none-any.whl size=6799 sha256=1890d596ad4b53ddb46fd0c34bf72610483f29d9b5eb31ce4b9216911f6723d1
  Stored in directory: /tmp/pip-ephem-wheel-cache-pv1s22ss/wheels/9b/39/aa/db3fab61f102c60eb7851fdda9ea6ddec4d85248d80625adbd
Successfully built jaxboard
Installing collected packages: jaxboard
Successfully installed jaxboard-0.0.1
moe@t1v-n-ff0a25ed-w-0:~$ 
```
